{
 "cells": [
  {
   "cell_type": "markdown",
   "source": [
    "# Evaluating Model Performance\n",
    "## Mapping Clinical Notes to Clinical Feature Code on NBME Data\n",
    "\n",
    "Source: https://www.kaggle.com/c/nbme-score-clinical-patient-notes\n",
    "\n",
    "Mary St. Jean\n",
    "****\n",
    "\n",
    "### Background\n",
    "I was invited to complete a technical challenge ahead of the technical interview. However, I was unable to access the linked dataset as it required credentialed access. Thus, I used analagous data to build models mapping natural language clinical notes to a relevant dependent variable. Mapping clinical notes to the variable, `feature` may aid in diagnosis by identifying recurrent symptoms or social determinants of health (SDOH).\n",
    "\n",
    "### Dependencies"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "outputs": [],
   "source": [
    "from constants import DATA_DIR\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pickle\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from keras.layers import Dense, Dropout, Conv1D, MaxPool1D, GlobalMaxPool1D, Embedding, Activation\n",
    "from keras.preprocessing.sequence import pad_sequences\n",
    "from keras.models import Sequential\n",
    "from gensim.models import KeyedVectors\n",
    "\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "outputs": [
    {
     "ename": "UnicodeDecodeError",
     "evalue": "'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mUnicodeDecodeError\u001B[0m                        Traceback (most recent call last)",
      "Cell \u001B[0;32mIn[46], line 13\u001B[0m\n\u001B[1;32m     11\u001B[0m features \u001B[38;5;241m=\u001B[39m  (pd\u001B[38;5;241m.\u001B[39mread_csv(\u001B[38;5;124mf\u001B[39m\u001B[38;5;124m'\u001B[39m\u001B[38;5;132;01m{\u001B[39;00mDATA_DIR\u001B[38;5;132;01m}\u001B[39;00m\u001B[38;5;124mtrain.csv\u001B[39m\u001B[38;5;124m'\u001B[39m))\n\u001B[1;32m     12\u001B[0m df_text \u001B[38;5;241m=\u001B[39m (pd\u001B[38;5;241m.\u001B[39mread_csv(\u001B[38;5;124mf\u001B[39m\u001B[38;5;124m'\u001B[39m\u001B[38;5;132;01m{\u001B[39;00mDATA_DIR\u001B[38;5;132;01m}\u001B[39;00m\u001B[38;5;124mpatient_notes.csv\u001B[39m\u001B[38;5;124m'\u001B[39m))\n\u001B[0;32m---> 13\u001B[0m w2v_model \u001B[38;5;241m=\u001B[39m \u001B[43mKeyedVectors\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mload_word2vec_format\u001B[49m\u001B[43m(\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m./word2vec.model\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mbinary\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[38;5;28;43;01mTrue\u001B[39;49;00m\u001B[43m)\u001B[49m\n\u001B[1;32m     17\u001B[0m \u001B[38;5;28mprint\u001B[39m(\u001B[38;5;124mf\u001B[39m\u001B[38;5;124m'''\u001B[39m\n\u001B[1;32m     18\u001B[0m \u001B[38;5;124m            -------------\u001B[39m\n\u001B[1;32m     19\u001B[0m \u001B[38;5;124m            Total unique features: \u001B[39m\u001B[38;5;132;01m{\u001B[39;00mfeatures\u001B[38;5;241m.\u001B[39mfeature_num\u001B[38;5;241m.\u001B[39mexplode()\u001B[38;5;241m.\u001B[39mnunique()\u001B[38;5;132;01m}\u001B[39;00m\n\u001B[1;32m     20\u001B[0m \u001B[38;5;124m            Total samples: \u001B[39m\u001B[38;5;132;01m{\u001B[39;00mdf_text\u001B[38;5;241m.\u001B[39mshape[\u001B[38;5;241m0\u001B[39m]\u001B[38;5;132;01m}\u001B[39;00m\n\u001B[1;32m     21\u001B[0m \u001B[38;5;124m            Data loaded!\u001B[39m\n\u001B[1;32m     22\u001B[0m \u001B[38;5;124m            \u001B[39m\u001B[38;5;124m'''\u001B[39m)\n",
      "File \u001B[0;32m~/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/gensim/models/keyedvectors.py:1719\u001B[0m, in \u001B[0;36mKeyedVectors.load_word2vec_format\u001B[0;34m(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype, no_header)\u001B[0m\n\u001B[1;32m   1672\u001B[0m \u001B[38;5;129m@classmethod\u001B[39m\n\u001B[1;32m   1673\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21mload_word2vec_format\u001B[39m(\n\u001B[1;32m   1674\u001B[0m         \u001B[38;5;28mcls\u001B[39m, fname, fvocab\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mNone\u001B[39;00m, binary\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mFalse\u001B[39;00m, encoding\u001B[38;5;241m=\u001B[39m\u001B[38;5;124m'\u001B[39m\u001B[38;5;124mutf8\u001B[39m\u001B[38;5;124m'\u001B[39m, unicode_errors\u001B[38;5;241m=\u001B[39m\u001B[38;5;124m'\u001B[39m\u001B[38;5;124mstrict\u001B[39m\u001B[38;5;124m'\u001B[39m,\n\u001B[1;32m   1675\u001B[0m         limit\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mNone\u001B[39;00m, datatype\u001B[38;5;241m=\u001B[39mREAL, no_header\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mFalse\u001B[39;00m,\n\u001B[1;32m   1676\u001B[0m     ):\n\u001B[1;32m   1677\u001B[0m \u001B[38;5;250m    \u001B[39m\u001B[38;5;124;03m\"\"\"Load KeyedVectors from a file produced by the original C word2vec-tool format.\u001B[39;00m\n\u001B[1;32m   1678\u001B[0m \n\u001B[1;32m   1679\u001B[0m \u001B[38;5;124;03m    Warnings\u001B[39;00m\n\u001B[0;32m   (...)\u001B[0m\n\u001B[1;32m   1717\u001B[0m \n\u001B[1;32m   1718\u001B[0m \u001B[38;5;124;03m    \"\"\"\u001B[39;00m\n\u001B[0;32m-> 1719\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[43m_load_word2vec_format\u001B[49m\u001B[43m(\u001B[49m\n\u001B[1;32m   1720\u001B[0m \u001B[43m        \u001B[49m\u001B[38;5;28;43mcls\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mfname\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mfvocab\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mfvocab\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mbinary\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mbinary\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mencoding\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mencoding\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43municode_errors\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43municode_errors\u001B[49m\u001B[43m,\u001B[49m\n\u001B[1;32m   1721\u001B[0m \u001B[43m        \u001B[49m\u001B[43mlimit\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mlimit\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mdatatype\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mdatatype\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mno_header\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mno_header\u001B[49m\u001B[43m,\u001B[49m\n\u001B[1;32m   1722\u001B[0m \u001B[43m    \u001B[49m\u001B[43m)\u001B[49m\n",
      "File \u001B[0;32m~/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/gensim/models/keyedvectors.py:2058\u001B[0m, in \u001B[0;36m_load_word2vec_format\u001B[0;34m(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype, no_header, binary_chunk_size)\u001B[0m\n\u001B[1;32m   2056\u001B[0m     fin \u001B[38;5;241m=\u001B[39m utils\u001B[38;5;241m.\u001B[39mopen(fname, \u001B[38;5;124m'\u001B[39m\u001B[38;5;124mrb\u001B[39m\u001B[38;5;124m'\u001B[39m)\n\u001B[1;32m   2057\u001B[0m \u001B[38;5;28;01melse\u001B[39;00m:\n\u001B[0;32m-> 2058\u001B[0m     header \u001B[38;5;241m=\u001B[39m \u001B[43mutils\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mto_unicode\u001B[49m\u001B[43m(\u001B[49m\u001B[43mfin\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mreadline\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mencoding\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mencoding\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m   2059\u001B[0m     vocab_size, vector_size \u001B[38;5;241m=\u001B[39m [\u001B[38;5;28mint\u001B[39m(x) \u001B[38;5;28;01mfor\u001B[39;00m x \u001B[38;5;129;01min\u001B[39;00m header\u001B[38;5;241m.\u001B[39msplit()]  \u001B[38;5;66;03m# throws for invalid file format\u001B[39;00m\n\u001B[1;32m   2060\u001B[0m \u001B[38;5;28;01mif\u001B[39;00m limit:\n",
      "File \u001B[0;32m~/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/gensim/utils.py:365\u001B[0m, in \u001B[0;36many2unicode\u001B[0;34m(text, encoding, errors)\u001B[0m\n\u001B[1;32m    363\u001B[0m \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28misinstance\u001B[39m(text, \u001B[38;5;28mstr\u001B[39m):\n\u001B[1;32m    364\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m text\n\u001B[0;32m--> 365\u001B[0m \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28;43mstr\u001B[39;49m\u001B[43m(\u001B[49m\u001B[43mtext\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mencoding\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43merrors\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43merrors\u001B[49m\u001B[43m)\u001B[49m\n",
      "\u001B[0;31mUnicodeDecodeError\u001B[0m: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte"
     ]
    }
   ],
   "source": [
    "# Load Data\n",
    "def load_data(fn, path=DATA_DIR):\n",
    "        with open(f'{path}{fn}.pkl', 'rb') as file:\n",
    "            df = pickle.load(file)\n",
    "        return df\n",
    "\n",
    "X_train = load_data(fn = 'x_train')\n",
    "X_test = load_data(fn = 'x_test')\n",
    "y_train = load_data(fn = 'y_train')\n",
    "y_test = load_data(fn = 'y_test')\n",
    "features =  (pd.read_csv(f'{DATA_DIR}train.csv'))\n",
    "df_text = (pd.read_csv(f'{DATA_DIR}patient_notes.csv'))\n",
    "w2v_model = KeyedVectors.load_word2vec_format(\"./word2vec.model\", binary=True)\n",
    "\n",
    "\n",
    "\n",
    "print(f'''\n",
    "            -------------\n",
    "            Total unique features: {features.feature_num.explode().nunique()}\n",
    "            Total samples: {df_text.shape[0]}\n",
    "            Data loaded!\n",
    "            ''')"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Random Forest Model"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "n_estimators = 10 depth =  5 : val_accuracy = nan\n",
      "n_estimators = 10 depth =  10 : val_accuracy = nan\n",
      "n_estimators = 10 depth =  15 : val_accuracy = nan\n",
      "n_estimators = 50 depth =  5 : val_accuracy = nan\n",
      "n_estimators = 50 depth =  10 : val_accuracy = nan\n",
      "n_estimators = 50 depth =  15 : val_accuracy = nan\n",
      "n_estimators = 100 depth =  5 : val_accuracy = nan\n",
      "n_estimators = 100 depth =  10 : val_accuracy = nan\n",
      "n_estimators = 100 depth =  15 : val_accuracy = nan\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "TypeError: float() argument must be a string or a number, not 'list'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/ensemble/_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 871, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/sklearn/utils/validation.py\", line 673, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/maryflanders/Documents/Career/tech_interview_basys/icd-prediction-mimic/python/lib/python3.9/site-packages/pandas/core/series.py\", line 1022, in __array__\n",
      "    arr = np.asarray(values, dtype=dtype)\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    }
   ],
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "name": "pycharm-766b5a82",
   "language": "python",
   "display_name": "PyCharm (tech_interview)"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}